### ISSUE TITLE
The results are not deterministic

### ISSUE THREAD

**Issue by Jalilifard** [DanielWarfield1/MLWritingAndResearch#1]
Hey,

I was testing your notebook **sslDemo.ipynb** and I am afraid to say that the results are different each time the code is run. Your conclusion is correct that the supervised method with the SSL backbone and random head is better than only the supervised model, however, the supervised model with the same head is sometimes better than the supervised and sometimes not.

I am wondering if you tested the results more than once and if so, how you made the results deterministic?

**Comment by DanielWarfield1** [comment]
I appreciate the interest!

This notebook isn't designed to create a deterministic demonstration of the theory. Because it's such a simplistic dataset, the models are so simple, and not a tone of care was taken in optimizing the training process, it makes sense that an element of stochasticity would result in results fluctuating away from theory.

I imagine, in a real use case with more complex images and a more complex task, where more care was taken in optimizing the training process, the difference might be more pronounced and more consistent. I would say, in this example, it's a "signal and noise" type of phenomenon.

**Comment by DanielWarfield1** [comment]
I think this issue is closed with the previous comment. Feel free to ask further questions as necessary, though.
